### ISSUE TITLE
Замечания по работе

### ISSUE THREAD

**Issue by AndriiLitvin** [OleksandrBazan/OleksandrBazan.github.io#1]
Визуально:
1) нет background на фоне(серый должен быть).
2)Должен быть border-radius и box-shadow в блока с контентом
3)Фото нужен border-radius + размер как на макете https://raw.githubusercontent.com/goit-fe/markup_fe2o/master/lesson_01/homework1.png

Код:
1)на теги лучше не натравливать стиля лучше делать через классы
2)Переход на другую строчку тоже лучше делать css тут http://joxi.ru/xAe0gQ1sogbO2y
если там есть тег "а" то ему присвоить display:block;
если нет вынести в другой тег если это span и тоже присвоить свойство display:block;

**Comment by AndriiLitvin** [comment]
1) нет background на фоне(серый должен быть). Где он? 
2) font-family: Arial; не он)
3) line-height - больше.
4) на картинке border-radius больше
5)Шрифты больше посмотри макет https://raw.githubusercontent.com/goit-fe/markup_fe2o/master/lesson_01/homework1.png
6)Вместо < hr > сделай блоку border-bottom

**Comment by OleksandrBazan** [comment]
у меня по первой работе зачет?

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
